import type { NextPage } from 'next';
import Head from 'next/head';
import { Counter } from '../features/counter/Counter';
import { Editor } from '../features/editor/Editor';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            width: '95vw',
            height: '80vh',
            alignContent: 'stretch',
            alignItems: 'center',
          }}
        >
          <div style={{ height: '30vh' }}>
            <h1 className={styles.title}>
              Welcome to <a href="https://tara.ai">Read Write!</a>
            </h1>
            <Counter />
          </div>

          <iframe
            style={{ flex: '1 1', width: '100%', height: '50vh' }}
            src={`http://localhost:4000/firestore/data/counter/global`}
          />
        </div>
      </main>
    </div>
  );
};

export default Home;
